
$mainMod = SUPER
$config = ~/.config/hypr/conf

source = $config/monitors.conf
source = $config/input.conf
source = $config/env.conf
source = $config/animations.conf
source = $config/looknfeel.conf
source = $config/bind.conf
source = $config/startup.conf
source = $config/rules.conf

