$active = rgba(136,192,208,1.0) 
$inactive = rgba(76,86,106,1.0)
general {
    gaps_in = 2
    gaps_out = 7

    border_size = 2

    col.active_border = $active
    col.inactive_border = $inactive

    resize_on_border = false
    allow_tearing = true

    layout = dwindle
}

decoration {
    rounding = 4

    active_opacity = 1.0
    inactive_opacity = 0.95

    shadow {
        enabled = false
        range = 8
        render_power = 5
        sharp = false
        color = rgba(000000A3)
        color_inactive = rgba(00000052)
        offset = 0 0
        scale = 1.0
    }

    blur {
        enabled = true
        size = 4
        passes = 4             
        new_optimizations = on 
        contrast = 1.0
        brightness = 1.0
        noise = 0.0065          
        vibrancy = 0.2 
    }
}

